version: "3"

services:
  db : 
    image : postgres
    restart : always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: postgres_gql
    ports:
      - '5432:5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data

  gql-go : 

    build : 
      context : ./GraphQL-Server
      dockerfile : Dockerfile

    environment :
      PORT: 3030
      ENV: Production

    depends_on : 
      - db

    ports : 
      - "3030:3030"

    networks :
      - default


  rest-go : 
    build : 
      context : ./REST-Server
      dockerfile : Dockerfile

    environment :
      PORT: 4040
      ENV: Production

    depends_on : 
      - db

    ports : 
      - "4040:4040"

    networks :
      - default

volumes:
  data:

